---
name: Bash CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bash-ci:
    name: Bash CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
            - 'bash/**'
      - name: Test exercises
        shell: bash
        if: steps.changes.outputs.src == 'true'
        run: ./.github/bin/run-bash-tests.sh
