---
name: Java CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golang-ci:
    name: Java CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
            - 'java/**'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Lint and test exercises
        shell: bash
        if: steps.changes.outputs.src == 'true'
        run: ./.github/bin/run-java-tests.sh
