---
name: Bash CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bash-ci:
    name: Bash CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
            - 'tracks/bash/**'
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.10.0
      - name: Test exercises
        shell: bash
        if: steps.changes.outputs.src == 'true'
        run: ./.github/bin/run-bash-tests.sh
