---
name: Golang CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golang-ci:
    name: Golang CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
            - 'tracks/go/**'
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.1
          cache: false
      - name: Lint and test exercises
        shell: bash
        if: steps.changes.outputs.src == 'true'
        run: ./.github/bin/run-go-tests.sh
