---

on:
  push: { }

name: CI - Go
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
      - name: Lint and Test exercises
        shell: bash
        run: |
          ./github/bin/fetch-golangci-lint
