---
name: Golang CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golang-ci:
    name: Golang CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
          cache: false
      - name: Lint and test exercises
        shell: bash
        run: ./.github/bin/run-go-tests.sh
