on:
  push: {}

name: CI - Go
jobs:
  checks:
    name: run
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3.1.0
      - name: Use Go 1.19
        uses: cedrickring/golang-action/go1.19@1.6.0
      - name: Custom project path
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "./go"
      - name: run
        uses: cedrickring/golang-action@1.6.0
