---

on:
  push: { }

name: CI - Go
jobs:
  golangci:
    name: Golang CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
      - name: Fetch Exercism
        shell: bash
        run: ./.github/bin/fetch-exercism.sh
      - name: Fetch GolangCI-Lint
        shell: bash
        run: ./.github/bin/fetch-golangci-lint.sh
      - name: Run Go Tests
        shell: bash
        run: ./.github/bin/run-go-tests.sh
