---
name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python-ci:
    name: Python CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
            - 'tracks/python/**'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Test exercises
        shell: bash
        if: steps.changes.outputs.src == 'true'
        run: |
          pip3 install pytest
          ./.github/bin/run-python-tests.sh
